import PySide2.Qt3DCore
import PySide2.QtCore
import shiboken2
import typing
T = typing.TypeVar('T')

class Qt3DLogic(shiboken2.Object):
    class QFrameAction(PySide2.Qt3DCore.Qt3DCore.QComponent):
        staticMetaObject: typing.ClassVar[PySide2.QtCore.QMetaObject] = ...
        triggered: typing.ClassVar[PySide2.QtCore.Signal] = ...
        def __init__(self, parent: typing.Optional[PySide2.Qt3DCore.Qt3DCore.QNode] = ..., addedToEntity: typing.Callable[..., typing.Any] = ..., defaultPropertyTrackingMode: Qt3DLogic.QFrameAction.PropertyTrackingMode = ..., defaultPropertyTrackingModeChanged: typing.Callable[..., typing.Any] = ..., destroyed: typing.Callable[..., typing.Any] = ..., enabled: bool = ..., enabledChanged: typing.Callable[..., typing.Any] = ..., isShareable: bool = ..., nodeDestroyed: typing.Callable[..., typing.Any] = ..., objectName: str = ..., objectNameChanged: typing.Callable[..., typing.Any] = ..., parentChanged: typing.Callable[..., typing.Any] = ..., removedFromEntity: typing.Callable[..., typing.Any] = ..., shareableChanged: typing.Callable[..., typing.Any] = ..., triggered: typing.Callable[..., typing.Any] = ...) -> None: ...

    class QLogicAspect(PySide2.Qt3DCore.Qt3DCore.QAbstractAspect):
        staticMetaObject: typing.ClassVar[PySide2.QtCore.QMetaObject] = ...
        def __init__(self, parent: typing.Optional[PySide2.QtCore.QObject] = ..., destroyed: typing.Callable[..., typing.Any] = ..., objectName: str = ..., objectNameChanged: typing.Callable[..., typing.Any] = ...) -> None: ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
